[package]
name = "infomagr"
version = "0.1.0"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]

[dependencies]
# glium = "0.13.5"
glium = { git = "https://github.com/tomaka/glium", rev = "a37c771" }
num_cpus = "0.2"
simd = { git = "https://github.com/rekka/simd", rev = "0ae5c4b" }
time = "0.1"
